### ISSUE TITLE
Problem with launching app

### ISSUE THREAD

**Issue by alexander-winkler** [dTsitsigkos/Amnesia#12]
I've got an issue similar to #7 . I've downloaded the application folder and set the permissions (`chmod -x nw`). When running `java -jar Amnesia.jar` from within the `amnesia-lin` directory, I see for a short moment a window with the title `Initializing`, then it aborts with the following STDERR output:

```
Alive
path = /home/user/amnesia-lin/amnesiaResults
87
65
82
78
73
78
71
58
32
65
110
32
105
108
108
101
103
97
108
32
114
101
102
108
101
99
116
105
118
101
32
97
99
99
101
115
115
32
111
112
101
114
97
116
105
111
110
32
104
97
115
32
111
99
99
117
114
114
101
100
10
87
65
82
78
73
78
71
58
32
73
108
108
101
103
97
108
32
114
101
102
108
101
99
116
105
118
101
32
97
99
99
101
115
115
32
98
121
32
111
114
103
46
115
112
114
105
110
103
102
114
97
109
101
119
111
114
107
46
99
103
108
105
98
46
99
111
114
101
46
82
101
102
108
101
99
116
85
116
105
108
115
36
49
32
40
106
97
114
58
102
105
108
101
58
47
104
111
109
101
47
97
108
101
120
47
68
111
119
110
108
111
97
100
115
47
97
109
110
101
115
105
97
45
108
105
110
47
97
109
110
101
115
105
97
66
97
99
107
69
110
100
45
49
46
48
45
83
78
65
80
83
72
79
84
46
106
97
114
33
47
66
79
79
84
45
73
78
70
47
108
105
98
47
115
112
114
105
110
103
45
99
111
114
101
45
52
46
51
46
53
46
82
69
76
69
65
83
69
46
106
97
114
33
47
41
32
116
111
32
109
101
116
104
111
100
32
106
97
118
97
46
108
97
110
103
46
67
108
97
115
115
76
111
97
100
101
114
46
100
101
102
105
110
101
67
108
97
115
115
40
106
97
118
97
46
108
97
110
103
46
83
116
114
105
110
103
44
98
121
Noe alive java
```

**Comment by Nikoc-dimako** [comment]
Maybe the port 8181 is not available, try to execute `fuser 8181/tcp` to see which pid  holds the port 8181. After that execute `kill -9 "pid"`and then re-run `java -jar Amnesia.jar`

**Comment by alexander-winkler** [comment]
Output of both `sudo fuser 8181/tcp` and `sudo ss -lptn 'sport = :8181'` is empty, so I guess that the port is not in use.

**Comment by Nikoc-dimako** [comment]
Could you tell me which java version are you using?

**Comment by alexander-winkler** [comment]
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

**Comment by Nikoc-dimako** [comment]
There is a problem in java 11 that I will fix it in the upcoming version of Amnesia. Could you downgrade in java 8?

**Comment by alexander-winkler** [comment]
great, changing to `openjdk version "1.8.0_292"` solved the problem, thank you!
