### ISSUE TITLE
Parse Problem: CSV file import

### ISSUE THREAD

**Issue by mobcdi** [dTsitsigkos/Amnesia#15]
I'm running v1.3.0 beta and I'm trying to import a csv file. I get the following error 
"Parse problem. Different size between title row and data row"

My csv has over 300 columns, its an export of an excel file and before I export it to csv I replace all commas with |  so the only delimiters will be introduced by the export process.  

1. Column titles are longer (verbose) than the data. 
2. Data is blank in places

Could either of those be causing the issue? The file opens fine in excel as a csv

**Comment by mobcdi** [comment]
Update: Seems the column titles can't be excessively long. I removed the long versions and used a shorter version and was able to progress to the data typing stage

**Comment by Nikoc-dimako** [comment]
Thanks for your feedback, maybe there was the delimiter character in the column titles.
 Please download the latest version of Amnesia 1.3.1 https://amnesia.openaire.eu/download.html in which some bugs were fixed.

**Comment by mobcdi** [comment]
Thanks for responding, I double checked the column titles and there wasn't any delimiter character but column title length ranged from 480 characters to 8 before I changed to a more manageable length range of 20 - 4 characters per title
