### ISSUE TITLE
Amnesia.jar refuses to start

### ISSUE THREAD

**Issue by eilmrein** [dTsitsigkos/Amnesia#7]
I downloaded the binary version from https://amnesia.openaire.eu/download.html.

When I run java -jar amnesia-lin/Amnesia.jar >out.txt 2>&1 (JDK 8, debian buster), I briefly see a window announcing "Wait for the application", then it terminates. It spits out the following text in the out.txt file:
Str java -Xms1024m -Xmx4096m -Dorg.eclipse.jetty.server.Request.maxFormKeys=1000000 -Dorg.eclipse.jetty.server.Request.maxFormContentSize=1000000 -jar /home/eilmrein/amnesia-lin/amnesiaBackEnd-1.0-SNAPSHOT.jar --server.port=8181 --trace
Alive
path = /home/eilmrein/amnesia-lin/amnesiaResults
Not alive nw

When I start the back-end (which works) before I run Amesia.jar, I get a little longer output
Str java -Xms1024m -Xmx4096m -Dorg.eclipse.jetty.server.Request.maxFormKeys=1000000 -Dorg.eclipse.jetty.server.Request.maxFormContentSize=1000000 -jar /home/eilmrein/amnesia-lin/amnesiaBackEnd-1.0-SNAPSHOT.jar --server.port=8181 --trace
Noe alive
Str2 java -Xms1024m -Dorg.eclipse.jetty.server.Request.maxFormKeys=1000000 -Dorg.eclipse.jetty.server.Request.maxFormContentSize=1000000 -jar /home/eilmrein/amnesia-lin/amnesiaBackEnd-1.0-SNAPSHOT.jar --server.port=8181 --trace
path = /home/eilmrein/amnesia-lin/amnesiaResults
Not alive nw

**Comment by Nikoc-dimako** [comment]
In amnesia-lin directory , the nw file needs to have executable permissions, so run `chmod +x nw` and then `java -jar Amnesia.jar`.

**Comment by eilmrein** [comment]
Thx for the hint - nw was executable, but libgconf2 was missing - works now!
May I suggest/help updating the README accordingly?

**Comment by Nikoc-dimako** [comment]
I will update the system requirements in the main website of Amnesia, thank you very much for your contribution
